
CREATE DATABASE IF NOT EXISTS nodetest;
USE nodetest;
CREATE TABLE IF NOT EXISTS Category (
  CategoryId INT AUTO_INCREMENT PRIMARY KEY,
  CategoryName VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS Product (
  ProductId INT AUTO_INCREMENT PRIMARY KEY,
  ProductName VARCHAR(100) NOT NULL,
  CategoryId INT,
  FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId) ON DELETE CASCADE
);
